version: 2

sources:
  - name: datamart
    description: "Raw data for bank marketing"
    schema: marketing
    tables:
      - name: raw_bank_marketing
        description: "Raw bank marketing dataset"
        columns:
          - name: age
            description: "Client's age"
          - name: job
            description: "Type of job. type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')"
          - name: marital
            description: "Marital status. marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)"
          - name: education
            description: "Education level. categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown'"
          - name: default
            description: "Has credit in default? (yes/no)"
          - name: balance
            description: "Average yearly balance in euros"
          - name: housing
            description: "Has a housing loan? (yes/no)"
          - name: loan
            description: "Has a personal loan? (yes/no)"
          - name: contact
            description: "Last contact communication type. (categorical: 'cellular','telephone'). Accept missing values"
          - name: day
            description: "Last contact day of the month"
          - name: month
            description: "Last contact month of the year. (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')"
          - name: duration
            description: "last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model."
          - name: campaign
            description: "number of contacts performed during this campaign and for this client (numeric, includes last contact)"
          - name: pdays
            description: "number of days that passed by after the client was last contacted from a previous campaign (numeric; -1 means client was not previously contacted)"
          - name: previous
            description: "number of contacts performed before this campaign and for this client"
          - name: poutcome
            description: "outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')"
          - name: y
            description: "Has the client subscribed to a term deposit? (yes/no)"


models:
  - name: stg_bank_marketing
    config:
      materialized: table
      contract:
        enforced: true
    columns:
      - name: age
        data_type: int
        constraints:
          - type: not_null
        tests:
          - is_natural_number
      - name: job
        data_type: string
        constraints:
          - type: not_null
        tests:
          - accepted_values:
              values: ['admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown']
          - not_empty_str
      - name: marital
        data_type: string
        constraints:
          - type: not_null
        tests:
          - accepted_values:
              values: ['divorced','married','single','unknown']
          - not_empty_str
      - name: education
        data_type: string
        constraints:
          - type: not_null
        tests:
          - accepted_values:
              values: ['secondary','primary','tertiary','basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown']
          - not_empty_str
      - name: default_
        data_type: bool
        constraints:
          - type: not_null
      - name: balance
        data_type: int
        constraints:
          - type: not_null
      - name: housing
        data_type: bool
        constraints:
          - type: not_null
      - name: loan
        data_type: bool
        constraints:
          - type: not_null
      - name: contact
        data_type: string
        constraints:
          - type: not_null
        tests:
          - accepted_values:
              values: ['cellular','telephone','unknown']
          - not_empty_str
      - name: day
        data_type: int
        constraints:
          - type: not_null
        tests:
          - is_less_than:
              number: 32
          - is_bigger_than:
              number: 0
      - name: month
        data_type: string
        constraints:
          - type: not_null
        tests:
          - accepted_values:
              values: ['apr','aug','dec','feb','jan','jul','jun','mar','may','nov','oct','sep']
          - not_empty_str
      - name: duration
        data_type: int
        constraints:
          - type: not_null
        tests:
          - is_bigger_than:
              number: -1
      - name: campaign
        data_type: int
        constraints:
          - type: not_null
        tests:
          - is_bigger_than:
              number: -1
      - name: pdays
        data_type: int
        tests:
          - is_bigger_than:
              number: -2
      - name: previous
        data_type: int
        constraints:
          - type: not_null
        tests:
          - is_bigger_than:
              number: -1
      - name: poutcome
        data_type: string
        tests:
          - accepted_values:
              values: [ 'other','failure','unknown','success' ]
      - name: y
        data_type: bool
        constraints:
          - type: not_null
